version: '3.1'
volumes: 
  imapsync_data: {}
services:
  imapsync:
    image: imapsync
    build: .
    command: "python main.py --config configs/config.ini"
    volumes:
      - imapsync_data:/var/data
    deploy:
      mode: global    

